[package]
name = "babystats"
version = "0.1.0"
authors = ["glenng"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
csv = "1.0.0-beta.3"
serde = "1"
serde_derive = "1"
serde_json = "1"
regex = "0.2.2"
lazy_static = "0.2"
